version: '3.9'

services:
  emby:
    image: emby/embyserver:latest
    container_name: emby_server
    environment:
      UID: 1000
      GID: 1000
      GIDLIST: 1000
    volumes:
      - filmes:/mnt/filmes
      - livros:/mnt/livros
      - config:/config
    ports:
      - "8096:8096"
      - "8920:8920"
    restart: unless-stopped

volumes:
  filmes:
  config:
  livros:
